# fly.toml app configuration file generated for part33 on 2023-12-27T15:20:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "part33"
primary_region = "mad"

[build]

[env]
  PORT="3002"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
